import {describe,expect,it} from 'vitest';import {anomalies,isStore,parseCsv,parseGapOverride,resolveGapMinutes} from './data';
import type {Batch} from './types';
describe('CSV 校验',()=>{it('解析合法 CSV',()=>{const r=parseCsv('时间,温度\n2026-09-01 08:00,25\n2026-09-01 09:00,120');expect(r.errors).toEqual([]);expect(r.samples).toHaveLength(2)});it('报告准确行号且拒绝部分导入',()=>{const r=parseCsv('时间,温度\n2026-09-01 09:00,100\n2026-09-01 08:00,abc');expect(r.errors.join(' ')).toContain('第 3 行');expect(r.samples).toEqual([])});it('拒绝重复时间',()=>{const r=parseCsv('时间,温度\n2026-09-01 08:00,25\n2026-09-01 08:00,30');expect(r.errors[0]).toContain('重复')});it('拒绝错误表头',()=>expect(parseCsv('time,temp\na,b').errors[0]).toContain('第 1 行'))});
describe('异常规则',()=>{it('生成超范围和间隔异常',()=>{const batch:any={samples:[{time:'2026-01-01T00:00',temperature:80},{time:'2026-01-01T02:00',temperature:100}],reviews:{}};const x=anomalies(batch,100,10,30);expect(x.map(v=>v.key)).toEqual(expect.arrayContaining(['range-2026-01-01T00:00','gap-2026-01-01T02:00']))})});
describe('备份校验',()=>{it('拒绝结构不完整对象',()=>expect(isStore({version:1,recipes:[],batches:[]})).toBe(false));it('缺少间隔覆盖字段的批次可加载',()=>{const legacy:any={version:1,gapMinutes:30,recipes:[{id:'r',name:'r',target:1,tolerance:1,duration:1}],batches:[{id:'b',name:'b',kiln:'k',recipeId:'r',start:'2026-09-01T00:00',notes:'',samples:[],reviews:{}}]};expect(isStore(legacy)).toBe(true)});it('覆盖字段不是数字时拒绝',()=>{const bad:any={version:1,gapMinutes:30,recipes:[],batches:[{id:'b',name:'b',kiln:'k',recipeId:'r',start:'x',notes:'',samples:[],reviews:{},gapMinutesOverride:'30'}]};expect(isStore(bad)).toBe(false)})});
describe('采样间隔阈值解析',()=>{
  const mk=(gapMinutesOverride?:number)=>{const b:Batch={id:'b',name:'b',kiln:'k',recipeId:'r',start:'x',notes:'',samples:[],reviews:{}};if(gapMinutesOverride!==undefined)b.gapMinutesOverride=gapMinutesOverride;return b};
  it('有自定义值用自定义值并标注批次来源',()=>expect(resolveGapMinutes(mk(10),45)).toEqual({value:10,source:'batch'}));
  it('缺少覆盖字段时回退统一值并标注全局来源',()=>expect(resolveGapMinutes(mk(),45)).toEqual({value:45,source:'global'}));
  it('空、非整数、小于 1 均拒绝',()=>{expect(parseGapOverride('').ok).toBe(false);expect(parseGapOverride('  ').ok).toBe(false);expect(parseGapOverride('1.5').ok).toBe(false);expect(parseGapOverride('abc').ok).toBe(false);expect(parseGapOverride('0').ok).toBe(false);expect(parseGapOverride('-3').ok).toBe(false)});
  it('正整数通过',()=>expect(parseGapOverride(' 30 ')).toEqual({ok:true,value:30}));
});
